---@type LangFile
return {
    misc = {
        text_disabled = "Disabled",
        text_star = "★",
        text_frame = "Frame",
        text_frame_plural = "Frames",
        text_none = "None",
        text_diamond = "◆",
        text_minute = "minute",
        text_minute_plural = "minutes",
        text_attempt = "attempt",
        text_attempt_plural = "attempts",
        text_quest_plural = "Quests",
        text_quest = "Quest",
    },
    menu = {
        config = {
            name = "Mod",
            enabled = "Enabled",
            reset = "Reset Settings",
            filter_quest_reference = "Filter Quest Reference",
            use_custom_list = "Use Custom List",
            tooltip_use_custom_list = "Pick quest from custom list instead of full list",
            tooltip_auto_post = "Auto Post immediately after returning from a quest",
            tooltip_auto_randomize = "Auto Randomize quest before posting",
            auto_post = "Auto Post",
            auto_randomize = "Auto Randomize",
            reload_quest_data = "Reload Quest Data",
        },
        language = {
            name = "Language",
            fallback = "Fallback",
            fallback_tooltip = "Display message in english if key is missing",
        },
        bind = {
            name = "Bind",
            tooltip_bound = "Already bound to",
            slider_buffer = "Buffer",
            tooltip_buffer = "Time window to detect multi-key combination (e.g. A+B) before triggering single keys",
            text_default = "Press any key...",
            button_add = "Add",
            button_save = "Save",
            button_remove = "Remove",
            button_cancel = "Cancel",
            button_clear = "Clear",
        },
        quest_ref = {
            name = "Quest Reference",
            tooltip_input_filter = "Quest Name Filter",
            header_name = "Quest Name",
            header_id = "Quest ID",
            header_map = "Map",
            header_level = "Level",
            header_custom_list = "Custom List",
            button_add = "Add",
            button_remove = "Remove",
            tooltip_quest_no = "Click to set Quest ID.",
        },
    },
    mod = {
        input_quest_id = "Quest ID",
        category_ignore_attr = "Exclude Quest Attributes",
        category_ignore_monster = "Exclude Monsters",
        category_ignore_map = "Exclude Maps",
        category_misc = "Misc",
        button_ignore = "Exclude",
        button_clear = "Clear",
        button_ignore_all = "Exclude All",
        combo_ignore_monster_state = {
            NONE = "Normal",
            NORMAL = "Tempered",
            KING = "Arch-Tempered",
            FRENZY = "Frenzied",
        },
        combo_ignore_monster_target = {
            SMALL = "Small Target",
            SINGLE = "Single Target",
            MULTI = "Multi Target",
        },
        combo_ignore_environ = {
            RUIN = "Ruin",
            ABNORMAL = "Abnormal",
            FERTILITY = "Fertility",
        },
        combo_ignore_quest_type = {
            MISSION = "Assignments",
            KEEP = "Investigations",
            FREE = "Optional Quests",
            EVENT = "Event Quests",
            ARENA = "Arena Quests",
            CHALLENGE = "Free Challenge Quests",
            INSTANT = "Field Survey",
        },
        combo_ignore_quest_target = {
            EM_BOSS_HUNTING = "Hunt",
            EM_BOSS_KILL = "Kill",
            EM_BOSS_CAPTURE = "Capture",
            ITEM = "Gathering",
            EM_BOSS_REMAIN_HP = "Repel",
        },
        radio_start_quest = {
            PICK = "Pick Quest",
            START_AND_DEPART = "Accept Quest & Depart",
            START_AND_PREP = "Accept Quest & Prep",
        },
        slider_text_time_limit = "With time limit shorter than %s %s",
        box_require_item_wishlist = "Wishlisted Item",
        box_require_item_rare = "Rare Item",
        box_require_boost = "Gathering Boost",
        box_require_current_stage = "Current Stage",
        box_require_spoffer = "Great Hunt",
        box_prefer_expiring_soon = "Prefer Expiring Soon",
        box_ignore_custom_list = "Custom List",
        tooltip_field = "Field Survey Only",
        tooltip_require_spoffer = "Multi Target quests",
        tooltip_item_rare = "'Shiny' items, plates, gems, etc.",
        tooltip_investigations_only = "Investigations/Field Survey Only",
        tooltip_prefer = "When multiple quests match your Prefer settings, they are ranked by how many preferences they satisfy.\nEach preference has a different importance:\nWishlisted Item > Rare Item > Specific Item > Great Hunt > Gathering Boost > Current Stage > Expiring Soon",
        tooltip_item_wishlist = "Bonus Rewards contain wishlisted item",
        tooltip_item_wishlist_any = "Any monster that can drop a wishlisted item (incl. guaranteed quest rewards & Investigation Bonus Rewards)",
        button_reset_posted = "Reset",
        button_reset_custom_list = "Reset",
        button_randomize = "Randomize",
        button_retry = "Retry Quest",
        button_post = "Post",
        tooltip_attempts = "Investigations only",
        text_legend = "Legend:",
        text_legend_disabled = "Disabled",
        text_legend_require = "Require",
        text_legend_prefer = "Prefer",
        tooltip_legend = "Require: Exclude quests that don't match the criteria\nPrefer: Pick matching quests first, if available",
        box_ignore_posted = "Posted",
        text_posted_quests = "%s %s",
        text_attempts_left = "%s %s remaining",
        box_ignore_completed = "Completed",
        box_ignore_non_acceptable = "Non-Acceptable",
        text_invalid_quest = "Invalid Quest",
        text_no_quest = "No Quests",
        tooltip_prefer_expiring_soon = "Expiring soon importance updates every 5 minutes. Quests expiring within the same window are treated equally.\ne.g. 1 min and 4 min remaining have the same importance, but 6 min does not",
        tooltip_radio_start_quest = "For Field Survey quests, Accept Quest & Prep is unavailable.\nIf selected, the quest will be started with Accept Quest & Depart",
    },
}
